-- ============================================================
-- IMPORTAÇÃO: 40 ESTÉTICAS DE BRASÍLIA → leads_crm
-- Origem: esteticas_brasilia.xlsx (Abril/2026)
-- Tier: A=nota>=4.8 & 50+ avals · B=nota>=4.5 · C=resto
-- NOTA: estes 40 registros já estavam no banco quando este arquivo
-- foi salvo (confirmado via tag 'importado' em leads_crm) — mantido
-- aqui apenas como registro/histórico, não precisa ser executado de novo.
-- ============================================================

INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('G30 Estética Automotiva', '', '+55 61 99405-8346', '', 'DF', 'Asa Norte', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.9 (190 avaliações). Asa Norte. SCRN 712/713, loja 30. Serviços: Polimento, Vitrificação, Higienização, Lavagem Motor', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('PHOENIX CAR CARE', '', '+55 61 99905-9131', '', 'DF', 'Asa Norte', 'matheus', 'C', 'prospecto', 0, 'Nota Google 4.4 (116 avaliações). Asa Norte. SCLRN 704 Bloco E, Loja 03. Serviços: Vitrificação, Higienização, Polimento, Restauração Faróis', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('4Gloss Brasília Estética Automotiva', '', '+55 61 98164-6287', '', 'DF', 'Asa Norte', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.9 (67 avaliações). Asa Norte. SCRN 704/705 Bloco C, Loja 06. Serviços: Polimento, Vitrificação, Limpeza Técnica Detalhada', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Car.9 Brasil - Detalhamento Automotivo', '', '+55 61 99989-9499', '', 'DF', 'Asa Norte', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.9 (167 avaliações). Asa Norte. SQN 309, Posto BR.. Serviços: Detalhamento Completo, Limpeza Motor, Higienização', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Boss Detail 305 Norte', '', '+55 61 99232-2851', '', 'DF', 'Asa Norte', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.8 (97 avaliações). Asa Norte. SHCN SQN 305 BL B. Serviços: Polimento, Vitrificação, Higienização, Martelinho', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Blue Motion Garage', '', '+55 61 99421-8921', '', 'DF', 'Asa Norte', 'matheus', 'A', 'prospecto', 0, 'Nota Google 5 (139 avaliações). Asa Norte. QD 704/705 BL F, Loja 46. Serviços: Vitrificação, Polimento, Higienização, PPF', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Poliwax Transmissões', '', '+55 61 98116-2229', '', 'DF', 'Asa Norte', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.8 (554 avaliações). Asa Norte. SCRN 706/707 Bloco B, Loja 38. Serviços: Produtos/Equipamentos, Polimento, Ceras, Vitrificadores', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Vogel Estética Automotiva', '', '+55 61 99951-4437', '', 'DF', 'Asa Norte', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (13 avaliações). Asa Norte. SCN Qd 04 - Shopping Liberty Mall. Serviços: Películas, Pintura, Vitrificação', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Boss Detail 713 Norte', '', '+55 61 3447-2925', '', 'DF', 'Asa Norte', 'matheus', 'B', 'prospecto', 0, 'Nota Google 4.7 (45 avaliações). Asa Norte. SQN 713 Bl A, Loja 09. Serviços: Estética, Polimento, Martelinho, Lavagem', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Pietros Car Estética Automotiva', '', '', '', 'DF', 'Asa Norte', 'matheus', 'B', 'prospecto', 0, 'Nota Google 4.7 (72 avaliações). Asa Norte. SCN Quadra 05 Bloco L. Serviços: Lavagem, Higienização, Estética', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Shine Lab Estética Automotiva', '', '+55 61 98581-5636', '', 'DF', 'Asa Sul', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.9 (59 avaliações). Asa Sul. SHCS 308/309, Bloco A. Serviços: Higienização, Polimento, Vitrificação, Martelinho, Assessoria', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Lubeck - Car & Coffee', '', '+55 61 99599-5380', '', 'DF', 'Asa Sul', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.8 (410 avaliações). Asa Sul. SQS 212 - Eixinho. Serviços: Lavagem Premium, Vitrificação, Polimento, Higienização', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Potenz Full Detailing', '', '+55 61 99416-5059', '', 'DF', 'Asa Sul', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.9 (71 avaliações). Asa Sul. SCS Quadra 09 - Parque Cidade Corporate. Serviços: Detalhamento, Vitrificação, Películas, Higienização', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('CARHAUS Lava Jato e Estética', '', '+55 61 3686-6450', '', 'DF', 'Asa Sul', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (1 avaliações). Asa Sul. SQS 302, Bloco A, PLL. Serviços: Lavagem, Estética Automotiva', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Trade Cars Estética Automotiva', '', '+55 61 98206-8274', '', 'DF', 'Asa Sul', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (1 avaliações). Asa Sul. SHCS SQS 309. Serviços: Estética, Polimento, Lavagem', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Solução do Polimento', '', '+55 61 98619-9859', '', 'DF', 'Cruzeiro', 'matheus', 'B', 'prospecto', 0, 'Nota Google 4.8 (23 avaliações). Cruzeiro. SRES AE - Cruzeiro Center. Serviços: Polimento, Higienização, Lavagem', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('JM Estética Automotiva', '', '+55 61 3553-8181', '', 'DF', 'Taguatinga Norte', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.9 (93 avaliações). Taguatinga Norte. Conj A, Lote 01, Loja 01 - QNL 12. Serviços: Lavagem Premium, Higienização, Limpeza Motor', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('XZL PINTURA e ESTÉTICA AUTOMOTIVA', '', '+55 61 98161-7083', '', 'DF', 'Taguatinga', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (15 avaliações). Taguatinga. QNE 4 - Taguatinga Norte. Serviços: Pintura, Polimento, Higienização, Martelinho, Atendimento Móvel', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('INOVE ESTÉTICA AUTOMOTIVA', '', '+55 61 98241-0000', '', 'DF', 'Taguatinga', 'matheus', 'B', 'prospecto', 0, 'Nota Google 4.9 (35 avaliações). Taguatinga. QNE 5 / QNE 12 - Taguatinga. Serviços: Polimento, Vitrificação, Higienização', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('ALL Black Estética Automotiva', '', '+55 61 99546-5995', '', 'DF', 'Taguatinga', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (1 avaliações). Taguatinga. Qs 5, 214-242 - Taguatinga. Serviços: Lavagem', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Th estética automotiva', '', '+55 61 98265-1935', '', 'DF', 'Taguatinga', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (16 avaliações). Taguatinga. Csg 09 lote 01 - Taguatinga. Serviços: Lavagem, Higienização, Estética', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('EstetiCar - Centro de Estética', '', '+55 61 99594-6718', '', 'DF', 'Taguatinga/Arniqueira', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.8 (172 avaliações). Taguatinga/Arniqueira. Rua 600, Qs 7 Rua 600, nº 08. Serviços: Higienização, Polimento, Lavagem', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Taguatinga - Estética Automotiva', '', '+55 61 3573-7073', '', 'DF', 'Taguatinga Sul', 'matheus', 'C', 'prospecto', 0, 'Nota Google 1 (1 avaliações). Taguatinga Sul. Qs 3, 19 - Loja 03. Serviços: Polimento Cristalizado, Películas, Lavagem', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Toretto Car Estética Automotiva', '', '+55 61 99366-1996', '', 'DF', 'Águas Claras', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (21 avaliações). Águas Claras. Av. das Araucárias, 525 - Posto Ipiranga. Serviços: Estética, Lavagem Detalhada, Polimento', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Estética automotiva Império Service', '', '+55 61 92004-5241', '', 'DF', 'Águas Claras', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (9 avaliações). Águas Claras. Al. dos Eucaliptos Q. 107, 9. Serviços: Higienização, Lavagem, Estética', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Shot Car - Soluções Automotivas', '', '+55 61 98489-0075', '', 'DF', 'Águas Claras', 'matheus', 'A', 'prospecto', 0, 'Nota Google 4.9 (94 avaliações). Águas Claras. Av. das Araucárias, 525 - Posto Ipiranga. Serviços: Higienização, Funilaria, Polimento, Lanternagem', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Castro Car Estética Automotiva', '', '+55 61 98532-5175', '', 'DF', 'Águas Claras', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (17 avaliações). Águas Claras. Estac. Subsolo -1 Vista Shopping. Serviços: Vitrificação, Polimento, Higienização Bancos', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Zeep Clean - Estética Automotiva', '', '+55 61 98171-6330', '', 'DF', 'Águas Claras', 'matheus', 'B', 'prospecto', 0, 'Nota Google 4.7 (85 avaliações). Águas Claras. Subsolo Condomínio Felicittà Shopping. Serviços: Higienização, Lavagem Completa', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Clean Car - Estética Automotiva', '', '+55 61 99379-1234', '', 'DF', 'Águas Claras', 'matheus', 'C', 'prospecto', 0, 'Nota Google 3.9 (38 avaliações). Águas Claras. 5º Andar - Shopping Águas Claras. Serviços: Higienização, Lavagem, Estética', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Multi carros Estética automotiva', '', '+55 61 98589-2614', '', 'DF', 'Águas Claras', 'matheus', 'B', 'prospecto', 0, 'Nota Google 4.5 (18 avaliações). Águas Claras. Qs 3 - Águas Claras. Serviços: Lanternagem, Polimento, Estética', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('HANG SHINE ESTÉTICA AUTOMOTIVA', '', '+55 61 99873-9249', '', 'DF', 'Águas Claras', 'matheus', 'C', 'prospecto', 0, 'Nota Google None (None avaliações). Águas Claras. Q. 301 Rua A, Conjunto 1, 7. Serviços: Higienização, Lavagem, Estética', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Guará Park Estética Automotiva', '', '+55 61 99259-3807', '', 'DF', 'Guará', 'matheus', 'B', 'prospecto', 0, 'Nota Google 4.5 (52 avaliações). Guará. Col. Agr. Águas Claras, Chácara 62 Lote 05. Serviços: Lavagem Americana, Enceramento, Cera', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Estética Automotiva No Talento', '', '+55 61 3522-3340', '', 'DF', 'Guará I', 'matheus', 'A', 'prospecto', 0, 'Nota Google 5 (86 avaliações). Guará I. QI 05 CL Bloco A, Loja 36. Serviços: Higienização, Limpeza Motor, Polimento Faróis', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('R2 estética automotiva full detail', '', '+55 61 99526-9445', '', 'DF', 'Guará II', 'matheus', 'C', 'prospecto', 0, 'Nota Google 4.4 (30 avaliações). Guará II. SRIA I, Conjunto I, Loja 2A - QE 40. Serviços: Vitrificação, Polimento, Higienização', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Fabrica do brilho estética automotiva', '', '+55 61 98231-3985', '', 'DF', 'Guará I', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (3 avaliações). Guará I. QI 18 - Guará. Serviços: Higienização, Polimento, Lavagem', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('RS Studio Automotivo Detailing', '', '+55 61 99831-5839', '', 'DF', 'Guará II', 'matheus', 'A', 'prospecto', 0, 'Nota Google 5 (50 avaliações). Guará II. QE 40 Conjunto D, Loja 01 Lote 60. Serviços: Vitrificação, Polimento, Higienização, Limpeza Motor', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Autotrato Estética Automotiva', '', '+55 61 98369-5964', '', 'DF', 'Guará II', 'matheus', 'B', 'prospecto', 0, 'Nota Google 4.6 (9 avaliações). Guará II. QE 40 Conjunto C, Lote 2. Serviços: Higienização, Polimento, Estética', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('SW Automotive', '', '', '', 'DF', 'Sudoeste', 'matheus', 'B', 'prospecto', 0, 'Nota Google 4.9 (19 avaliações). Sudoeste. Segunda Avenida - Sudoeste. Serviços: Estética, Polimento, Higienização', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Sudocar estética Automotiva', '', '+55 61 99195-6750', '', 'DF', 'Sudoeste/SIG', 'matheus', 'B', 'prospecto', 0, 'Nota Google 5 (2 avaliações). Sudoeste/SIG. SIG Quadra 2 - Ed. City Offices. Serviços: Lavagem, Estética Automotiva', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;
INSERT INTO public.leads_crm (nome_empresa, nome_contato, telefone, email, regiao, cidade, responsavel, tier, status, valor_medio_mensal, notas, tipo_estabelecimento, historico_interacoes, tags, tenant_id) VALUES ('Aura Lava Jato - 306 Sul', '', '', '', 'DF', 'Asa Sul', 'matheus', 'C', 'prospecto', 0, 'Nota Google None (None avaliações). Asa Sul. SQS 306 - Posto. Serviços: Lavagem, Limpeza', 'estetica', '[]'::jsonb, ARRAY['brasilia','importado']::text[], 'a1b2c3d4-e5f6-7890-abcd-ef1234567890') ON CONFLICT DO NOTHING;

SELECT 'esteticas importadas' as status, count(*) FROM leads_crm WHERE 'importado' = ANY(tags);
